#
# Build the project

name: build

env:
  MAJOR: 0
  MINOR: 0
  JAVA_VERSION: 17

on:
  workflow_call

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - name: Construct build version
      id: construct
      run: |
        VERSION="${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"
        if [ "$GITHUB_REF" == 'refs/heads/main' ]; then
          IS_RELEASE=true
          echo "::notice ::Building release ${VERSION}"
          echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
        else
          VERSION="${VERSION}-SNAPSHOT"
          echo "::notice ::Building version ${VERSION}"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.construct.outputs.VERSION }}
      is_release: ${{ steps.construct.outputs.IS_RELEASE }}

  build:
    runs-on: ubuntu-latest
    needs: version
    steps:

    - name: Checkout out our code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup a cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}
        path: |
          ~/.gradle

    - name: Build
      env:
        MRMAT_VERSION: ${{ needs.version.outputs.version }}
      run: |
        echo "::notice ::Building release ${VERSION}"
        ./gradlew --no-daemon build
