#
# Continuous Integration

name: CI

#
# Establish when the workflow is run.
# We run on all branches except main, for which the release workflow applies

on:
  push:
    branches-ignore:
    - main

#
# Workflow

jobs:
  build:
    uses: ./.github/workflows/build.yml
