#
# Build the project

name: Build

#
# Operational Variables

env:
  JAVA_VERSION: 17

#
# Establish when the workflow is run.
# We run on all branches except main, for which the release workflow applies

on:
  push:
    branches-ignore:
    - main

#
# Workflow

jobs:
  version:
    uses: ./.github/workflows/version.yml

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout out our code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: Setup a cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper

    - name: Build
      env:
        MRMAT_VERSION: ${{ needs.version.outputs.MRMAT_VERSION }}
      run: ./gradlew build
