#
# This workflow triggers checks for a PR and then a release when it is merged

name: pr-checks
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "The PR was checked"

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Conditional Release
      uses: marvinpinto/action-automatic-releases@latest
      if: (github.event.pull_request.merged == true)
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.MRMAT_VERSION }}"
        prerelease: false
        title: "Release ${{ env.MRMAT_VERSION }}"
