#
# This workflow triggers for a release via a PR to main. It runs in the context of the base branch (main)

name: pr-release
on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Conditional Release
      uses: marvinpinto/action-automatic-releases@latest
      if: (github.event.pull_request.merged == true)
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.MRMAT_VERSION }}"
        prerelease: false
        title: "Release ${{ env.MRMAT_VERSION }}"
