#
# Perform a PR check build

name: pr

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

permissions:
  pull-requests: write

env:
  JAVA_VERSION: 17

#
# Workflow

jobs:
  version:
    uses: ./.github/workflows/version.yml

  checks:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - name: Checkout out our code
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        add-job-summary-as-pr-comment: 'always'
    - name: Build
      env:
        MRMAT_VERSION: ${{ needs.version.outputs.version }}
      run: |
        echo "::notice ::Building PR check build ${MRMAT_VERSION}"
        ./gradlew --no-daemon build testCodeCoverageReport testAggregateTestReport
    - name: Report on Unit tests
      if: ${{ !cancelled() }}
      uses: dorny/test-reporter@v2
      with:
        name: JUnit Tests
        reporter: java-junit
        path: '**/build/test-results/test/*.xml'
        fail-on-error: false
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.2
      with:
        paths: |
          ${{ github.workspace }}/build/reports/jacoco/**/testCodeCoverageReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
