#
# This workflow triggers checks for a PR and then a release when it is merged

name: release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Conditional Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.MRMAT_VERSION }}"
        prerelease: false
        title: "Release ${{ env.MRMAT_VERSION }}"
