#
# This workflow triggers checks for a PR and then a release when it is merged

name: release
on:
  push:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version.outputs.version }}
        release_name: Release ${{ needs.version.outputs.version }}
        body: |
          Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: false
