#
# This workflow triggers checks for a PR and then a release when it is merged

name: release

on:
  push:
    branches: [main]

permissions:
  contents: write

env:
  JAVA_VERSION: 17

jobs:
  version:
    uses: ./.github/workflows/version.yml

  build:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - name: Checkout out our code
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      env:
        MRMAT_VERSION: ${{ needs.version.outputs.version }}
      run: |
        echo "::notice ::Building release ${MRMAT_VERSION}"
        ./gradlew --no-daemon build
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.version.outputs.version }}
        release_name: Release ${{ needs.version.outputs.version }}
        body: |
          Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: false
