env:
  MAJOR: 0
  MINOR: 0

name: version
on:
  workflow_call

jobs:
  construct:
    runs-on: ubuntu-latest
    steps:
    - name: Construct build version
      id: construct
      run: |
        VERSION="${MAJOR}.${MINOR}.${GITHUB_RUN_NUMBER}"
        if [ "$GITHUB_REF" == 'refs/heads/main' ]; then
          IS_RELEASE=true
          echo "::notice ::Building release ${VERSION}"
          echo "IS_RELEASE=true" >> $GITHUB_OUTPUT
        else
          VERSION="${VERSION}-SNAPSHOT"
          echo "::notice ::Building version ${VERSION}"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.construct.outputs.VERSION }}
      is_release: ${{ steps.construct.outputs.IS_RELEASE }}
